//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4216
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guineu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guineu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guineu.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity error: {0}.
        /// </summary>
        internal static string Error_ConnectivityError {
            get {
                return ResourceManager.GetString("Error_ConnectivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type mismatch..
        /// </summary>
        internal static string Error_DataTypeMismatch {
            get {
                return ResourceManager.GetString("Error_DataTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is in use..
        /// </summary>
        internal static string Error_FileIsInUse {
            get {
                return ResourceManager.GetString("Error_FileIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is read-only..
        /// </summary>
        internal static string Error_PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("Error_PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Error.
        /// </summary>
        internal static string Execution_Error {
            get {
                return ResourceManager.GetString("Execution_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string F_CMonth_April {
            get {
                return ResourceManager.GetString("F_CMonth_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string F_CMonth_August {
            get {
                return ResourceManager.GetString("F_CMonth_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string F_CMonth_December {
            get {
                return ResourceManager.GetString("F_CMonth_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string F_CMonth_February {
            get {
                return ResourceManager.GetString("F_CMonth_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string F_CMonth_January {
            get {
                return ResourceManager.GetString("F_CMonth_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string F_CMonth_July {
            get {
                return ResourceManager.GetString("F_CMonth_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string F_CMonth_June {
            get {
                return ResourceManager.GetString("F_CMonth_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string F_CMonth_March {
            get {
                return ResourceManager.GetString("F_CMonth_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string F_CMonth_May {
            get {
                return ResourceManager.GetString("F_CMonth_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string F_CMonth_November {
            get {
                return ResourceManager.GetString("F_CMonth_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string F_CMonth_October {
            get {
                return ResourceManager.GetString("F_CMonth_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string F_CMonth_September {
            get {
                return ResourceManager.GetString("F_CMonth_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Overwrite it?.
        /// </summary>
        internal static string FileExistsOverwrite {
            get {
                return ResourceManager.GetString("FileExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown ADD statement.
        /// </summary>
        internal static string Unknown_ADD_statement {
            get {
                return ResourceManager.GetString("Unknown_ADD_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is undefinied.
        /// </summary>
        internal static string Value_Is_Undefined {
            get {
                return ResourceManager.GetString("Value_Is_Undefined", resourceCulture);
            }
        }
    }
}
